os:
    - linux
    - osx
language: cpp
dist: bionic
sudo: required

before_install:
    - ./.travis/before_install.sh

install:
    - ./.travis/install.sh

before_script:
    - mkdir -p build
    - cd build
    - ../.travis/before_script.sh

script: make

after_success:
    - cd ..
    - ./.travis/after_success.sh 

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    local_dir: build/doc/html
    on:
        condition: "$TRAVIS_OS_NAME == linux"

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: "build/Radiance.AppDir.tar.gz"
    on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_OS_NAME == linux"
    overwrite: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: "build/Radiance.dmg"
    on:
        condition: "$TRAVIS_OS_NAME == osx"
        tags: true
        all_branches: true
    overwrite: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: "deploy/build/radiance_$TRAVIS_TAG-1_amd64.deb"
    on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_OS_NAME == linux"
    overwrite: true
